[build-system]
requires = [
    "setuptools >= 61.0",
    "wheel",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "hubnado"
authors = [
    {name = "Alastair Smith", email = "alastair.smith@ndcls.ox.ac.uk"},]
description = "CLI library to generate UCSC trackhubs from sequencing data"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "GNU GENERAL PUBLIC LICENSE Version 3"}
dynamic = ["version"]
dependencies = [
    "click",
    "pandas",
    "cookiecutter",
    "setuptools_scm",
    "seaborn",
    "trackhub",
    "Pillow",
]

[project.scripts]
hubnado = "hubnado.cli:cli"

[tool.setuptools_scm]
write_to = "hubnado/_version.py"
local_scheme = "no-local-version"

[project.urls]